[project]
name = "web-scrapping-meteo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ruff>=0.8.6",
    "tqdm>=4.67.1",
]
